### ISSUE TITLE
vault/vault was not found

### ISSUE THREAD

**Issue by martindanko** [UKHomeOffice/docker-vault#4]
When attempting to provision this I get the following error in events.

> Error creating: pods "vault-1232930497-" is forbidden: service account vault/vault was not found, retry after the service account is created

Even though the **vault** namespace and **vault** ServiceAccount exist.

I'm trying this with the released 0.2.1 version of docker-vault on Kubernetes version 1.4

**Comment by vaijab** [comment]
> Even though the vault namespace and vault ServiceAccount exist.

How do you manage authorization? If you use ABAC, then check `auth-policy.json` to make sure that the service account you created has access to the API.

**Comment by martindanko** [comment]
Thanks for your quick response. I just discovered it was because the service account I created was in the incorrect namespace. Apologies for taking up your time.

**Comment by vaijab** [comment]
No worries. :-)
