### ISSUE TITLE
Is this supposed to be public?

### ISSUE THREAD

**Issue by myllk** [UKHomeOffice/docker-vault#5]
In docker-vault/kube/vault-deployment.yaml there are env vars like AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and VAULT_ADMIN_PASSWORD. 

Are these supposed to be public?? Sorry if these are dummy keys or something, just seemed slightly alarming...

**Comment by oyelekci** [comment]
They're dummy creds, thanks.
